export const HELP_CONTENT = [
  {
    id: 'welcome',
    title: 'Welcome to Prompt Refinery',
    body: [
      { type: 'text', text: 'Prompt Refinery takes your rough ideas and refines them into clear, well-structured prompts you can use with any AI assistant. Better prompts produce better results.' },
      { type: 'text', text: 'You type a casual prompt, pick a category, and get back two things: a refined version of your prompt, and a list of exactly what changed and why. Prompt Refinery is built to teach, not just transform.' },
    ],
  },
  {
    id: 'tutorial',
    title: 'Step-by-step tutorial',
    body: [
      { type: 'step', n: 1, title: 'Pick a category', text: 'Above the input area, you\'ll see five category chips. Click the one that matches your task. Each category tunes the refinement to that kind of writing.' },
      { type: 'step', n: 2, title: 'Type a rough prompt', text: 'Don\'t worry about being polished. "Write me an email about a project delay" is enough. The app will fill in the structure for you.' },
      { type: 'step', n: 3, title: 'Submit', text: 'Click the arrow button on the right, or press Cmd+Enter (Ctrl+Enter on Windows/Linux). The refined prompt will appear within a few seconds.' },
      { type: 'step', n: 4, title: 'Read what changed', text: 'Below the refined prompt, you\'ll see a "What changed" panel listing the specific improvements that were made and why. This is the teaching part. Read it.' },
      { type: 'step', n: 5, title: 'Copy and use it', text: 'Click the Copy button at the top of the refined prompt. Paste it into Claude, ChatGPT, or wherever you\'re working.' },
      { type: 'step', n: 6, title: 'Revisit history', text: 'Every refinement is automatically saved. Click the History icon in the left rail to see your recent prompts.' },
    ],
  },
  {
    id: 'whatchanged',
    title: 'The "What changed" panel',
    body: [
      { type: 'text', text: 'This is the feature that makes Prompt Refinery different from a simple AI wrapper. Every time the app refines your prompt, it also returns a numbered list of the specific changes it made and why each one helps.' },
      { type: 'text', text: 'The panel shows 3-6 changes per refinement, ordered from most impactful to least. Each item has a short title and a one-sentence explanation.' },
      { type: 'list', items: [
        { label: 'Read every time', text: 'Don\'t just copy the refined prompt — read what changed. Over time, you\'ll absorb the patterns.' },
        { label: 'Compare across categories', text: 'Try the same rough prompt with different categories. The differences in what changes tell you a lot about each category\'s philosophy.' },
        { label: 'Notice the empty cases', text: 'If a prompt was already well-formed, the app may show only 1-2 changes. That\'s a signal you\'re writing good prompts already.' },
      ]},
      { type: 'note', text: 'The "What changed" list is generated by the AI alongside the refined prompt. Like the refinement itself, the explanations reflect general prompting best practices but may occasionally be subjective.' },
    ],
  },
  {
    id: 'categories',
    title: 'Categories',
    body: [
      { type: 'text', text: 'Each category gives the AI different instructions for how to refine your prompt:' },
      { type: 'list', items: [
        { label: 'General', text: 'Adds structure, specificity, and clear output format. Use when none of the others quite fit.' },
        { label: 'Writing', text: 'Tunes for creative or professional writing tasks. Adds audience, tone, length, and voice guidance.' },
        { label: 'Code', text: 'Tunes for software tasks. Adds language, input/output spec, edge cases, and constraints.' },
        { label: 'Analysis', text: 'Tunes for research and analysis. Adds output structure, questions to answer, and asks for citations.' },
        { label: 'Brainstorm', text: 'Tunes for idea generation. Specifies number of ideas, categorization, and evaluation criteria.' },
      ]},
    ],
  },
  {
    id: 'history',
    title: 'History',
    body: [
      { type: 'text', text: 'Your last 20 refinements are saved locally in your browser. They survive page refreshes and stay private to your device.' },
      { type: 'text', text: 'Open history from the left rail. Click any entry to reload both the rough prompt and its refined version, along with the "What changed" panel.' },
      { type: 'note', text: 'Clearing your browser data also clears history. If you want to keep a refined prompt long-term, copy it somewhere safe.' },
    ],
  },
  {
    id: 'settings',
    title: 'Settings & model selection',
    body: [
      { type: 'text', text: 'Open Settings from the left rail. You can choose which AI model refines your prompts. Claude Sonnet 4.6 is the default — a strong balance of capability and cost.' },
      { type: 'list', items: [
        { label: 'Claude Opus 4.7', text: 'Most capable. Best for complex prompts where you need the most thoughtful refinement.' },
        { label: 'Claude Sonnet 4.6', text: 'Default. Balanced workhorse. Recommended for most use cases.' },
        { label: 'Claude Opus 4.6', text: 'The previous flagship. Still highly capable.' },
        { label: 'Claude Haiku 4.5', text: 'Fastest and cheapest. Good for short, simple prompts at volume.' },
      ]},
      { type: 'text', text: 'Other providers (OpenAI GPT, Google Gemini) are listed as "coming soon."' },
      { type: 'note', text: 'Pro vs API billing: A Claude Pro subscription covers chat at claude.ai. This app uses Anthropic\'s API through a separate console account, so every refinement uses your API credits regardless of which model you select.' },
    ],
  },
  {
    id: 'shortcuts',
    title: 'Keyboard shortcuts',
    body: [
      { type: 'list', items: [
        { label: 'Cmd+Enter', text: 'Submit the prompt (Ctrl+Enter on Windows/Linux).' },
      ]},
    ],
  },
  {
    id: 'tips',
    title: 'Tips for better prompts',
    body: [
      { type: 'text', text: 'Even the rough version benefits from a little context. The more specific your input, the more useful the refined version will be.' },
      { type: 'list', items: [
        { label: 'Mention the audience', text: 'Who will read or use the result? Their expertise level matters.' },
        { label: 'Mention the format', text: 'Email, blog post, code review, summary, table — say it.' },
        { label: 'Mention constraints', text: 'Length limits, tone, what to avoid.' },
        { label: 'Use the right category', text: 'Picking "Code" for a writing task wastes the refinement.' },
      ]},
    ],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    body: [
      { type: 'list', items: [
        { label: '"Something went wrong"', text: 'Usually means the backend server isn\'t running, or your API key is invalid.' },
        { label: '"Unexpected response format"', text: 'Occasionally the AI returns something we can\'t parse. Just try again — almost always works on retry.' },
        { label: 'Slow responses', text: 'Each refinement calls the AI over the network. 2-5 seconds is normal. Opus models can take longer for complex prompts.' },
        { label: 'History disappeared', text: 'Most likely your browser cleared its local data.' },
        { label: 'Model error', text: 'If a specific Claude model fails, switch back to the default in Settings.' },
      ]},
    ],
  },
];
