export const HELP_CONTENT = [
  {
    id: 'welcome',
    title: 'Welcome to Prompt Refinery',
    body: [
      { type: 'text', text: 'Prompt Refinery takes your rough ideas and refines them into clear, well-structured prompts you can use with any AI assistant. Better prompts produce better results.' },
      { type: 'text', text: 'After each refinement you get three things: the refined prompt itself, a "What changed" panel explaining the improvements, and a Quality score panel showing both your rough prompt and the refined version scored across five named dimensions — side by side, so you can see exactly where the lift came from.' },
    ],
  },
  {
    id: 'tutorial',
    title: 'Step-by-step tutorial',
    body: [
      { type: 'step', n: 1, title: 'Pick a category', text: 'Above the input area, you\'ll see five category chips. Click the one that matches your task.' },
      { type: 'step', n: 2, title: 'Type a rough prompt — or use a template', text: 'Don\'t worry about being polished. "Write me an email about a project delay" is enough.' },
      { type: 'step', n: 3, title: 'Submit', text: 'Click the arrow button on the right, or press Cmd+Enter (Ctrl+Enter on Windows/Linux). The refined prompt streams in within milliseconds.' },
      { type: 'step', n: 4, title: 'Read what changed', text: 'Below the refined prompt, the "What changed" panel lists the specific improvements made and why each helps.' },
      { type: 'step', n: 5, title: 'Study the quality scores', text: 'Below "What changed," the Quality score panel shows two radar charts — your rough prompt on the left, the refined version on the right. Below them, each dimension is broken down with both rationales side by side: what was weak about your rough version, and what the refinement did differently.' },
      { type: 'step', n: 6, title: 'Refine further if needed', text: 'Use the quick presets or type custom feedback. The refinement updates in place along with new changes and scores.' },
      { type: 'step', n: 7, title: 'Copy or save the final version', text: 'Click Copy to copy the refined prompt, or the star to save it permanently.' },
    ],
  },
  {
    id: 'quality-score',
    title: 'Quality score',
    body: [
      { type: 'text', text: 'Every refinement is scored 1-5 across five dimensions that define a well-structured prompt. Both your rough prompt and the refined version are scored, so you can see exactly where the lift came from.' },
      { type: 'list', items: [
        { label: 'Specificity', text: 'How concrete and detailed is the request? Vague asks score low; precise asks with named entities, quantities, and context score high.' },
        { label: 'Audience', text: 'Does the prompt establish who the response is for and what they need? Implicit audience scores low; explicitly-named audience with expertise level scores high.' },
        { label: 'Format', text: 'Is the desired output format specified? "Just answer" scores low; "Return a markdown table with columns X, Y, Z" scores high.' },
        { label: 'Constraints', text: 'Are limits, exclusions, and edge cases stated? Unbounded prompts score low; ones with explicit constraints (length, tone, what to avoid) score high.' },
        { label: 'Examples', text: 'Does the prompt include examples or ask for step-by-step reasoning? No guidance scores low; concrete examples or chain-of-thought requests score high.' },
      ]},
      { type: 'text', text: 'Each dimension shows both rationales — labeled "Rough" and "Refined" — so you understand precisely what was weak in your original phrasing and what the refinement did to address it. The green "+X" badges next to each score show the lift for that dimension at a glance.' },
      { type: 'text', text: 'This is the part of the app designed for learning. Over many refinements, you\'ll start to notice patterns: maybe your rough prompts consistently score low on Format, or you reliably forget Constraints. Use that to write better rough prompts over time.' },
      { type: 'note', text: 'Scores are generated by the AI alongside the refinement. Treat them as directional — useful for spotting weak dimensions and tracking your improvement, not as objective truth. An AI grading its own work has obvious limitations.' },
    ],
  },
  {
    id: 'followup',
    title: 'Refine further',
    body: [
      { type: 'text', text: 'After each refinement, a "Refine further" panel appears below the score. Use it to iterate without starting over.' },
      { type: 'list', items: [
        { label: 'Quick presets', text: '"Shorter," "More formal," "Simpler," and "Add examples" apply common feedback in one click.' },
        { label: 'Custom feedback', text: 'Type any feedback into the input field. "Add a section on cost," "make it more friendly" — anything you\'d say to a colleague editing a draft.' },
        { label: 'Submitting', text: 'Press Enter or click the arrow. The refinement, changes, and scores all update for the new iteration.' },
      ]},
      { type: 'note', text: 'Each follow-up replaces the previous result. If you want to keep an earlier version, save it (with the star) before refining further. The "rough" score in a follow-up still refers to your original input, not the previous refined version.' },
    ],
  },
  {
    id: 'streaming',
    title: 'How streaming works',
    body: [
      { type: 'text', text: 'When you submit a prompt, the refined version streams in word by word rather than appearing all at once. The "What changed" and Quality score panels appear once streaming completes.' },
      { type: 'list', items: [
        { label: 'The pulsing dot', text: 'A small dot next to "Refined prompt" pulses while the AI is generating.' },
        { label: 'The caret', text: 'The blinking line at the end of the text shows where the next character will land.' },
        { label: 'The stop button', text: 'The send button becomes a stop button (square) during streaming. Click it to cancel.' },
        { label: 'Locked controls', text: 'While streaming, the textarea and action buttons are disabled to prevent confusing state changes.' },
      ]},
    ],
  },
  {
    id: 'saved',
    title: 'Saved prompts',
    body: [
      { type: 'text', text: 'History is automatic but rolling — only your last 20 refinements stay. Saved prompts are the ones you want to keep permanently, along with their changes and score data.' },
      { type: 'text', text: 'To save a refinement, click the star icon at the top right of any refined prompt. The icon fills in to confirm. Click again to unsave.' },
      { type: 'list', items: [
        { label: 'View saved prompts', text: 'Open Saved from the left rail (the star icon).' },
        { label: 'Rename them', text: 'Hover any saved prompt to reveal Rename and Remove buttons.' },
        { label: 'Reload a saved prompt', text: 'Click any saved prompt to load it along with its refined version, "What changed" panel, and Quality score.' },
        { label: 'Remove when done', text: 'Click the trash icon on any saved prompt.' },
      ]},
      { type: 'note', text: 'Saved prompts are stored locally in your browser. Clearing browser data will remove them.' },
    ],
  },
  {
    id: 'templates',
    title: 'Templates',
    body: [
      { type: 'text', text: 'If you\'re not sure where to start, open Templates from the left rail. Common scenarios are grouped by category.' },
      { type: 'text', text: 'Click any template to load it into the composer. The rough prompt and matching category are filled in for you.' },
      { type: 'list', items: [
        { label: 'Edit before submitting', text: 'Templates are starting points, not exact prompts.' },
        { label: 'Compare categories', text: 'Try the same template under different categories to see how the refinement and scores change.' },
        { label: 'Save the good ones', text: 'After refining a template, star it to keep your customized version.' },
      ]},
    ],
  },
  {
    id: 'whatchanged',
    title: 'The "What changed" panel',
    body: [
      { type: 'text', text: 'This panel shows the specific changes the refinement made and why each helps. It appears once the refined prompt finishes streaming.' },
      { type: 'text', text: '3-6 changes per refinement, ordered from most impactful to least. Each has a short title and a one-sentence explanation.' },
      { type: 'list', items: [
        { label: 'Read every time', text: 'The explanations are how you learn the patterns.' },
        { label: 'Follow-ups have their own', text: 'When you refine further, the panel updates to show what changed in that iteration specifically.' },
      ]},
    ],
  },
  {
    id: 'categories',
    title: 'Categories',
    body: [
      { type: 'text', text: 'Each category gives the AI different instructions for how to refine your prompt:' },
      { type: 'list', items: [
        { label: 'General', text: 'Adds structure, specificity, and clear output format.' },
        { label: 'Writing', text: 'Tunes for creative or professional writing.' },
        { label: 'Code', text: 'Tunes for software tasks.' },
        { label: 'Analysis', text: 'Tunes for research and analysis.' },
        { label: 'Brainstorm', text: 'Tunes for idea generation.' },
      ]},
    ],
  },
  {
    id: 'history',
    title: 'History',
    body: [
      { type: 'text', text: 'Your last 20 refinements — including follow-up iterations — are saved locally in your browser, with their changes and scores preserved.' },
      { type: 'text', text: 'Open history from the left rail. Click any entry to reload everything. Follow-up entries are marked with a small "follow-up" tag.' },
      { type: 'note', text: 'History is a rolling list. To keep a prompt permanently, star it.' },
    ],
  },
  {
    id: 'settings',
    title: 'Settings & model selection',
    body: [
      { type: 'text', text: 'Open Settings from the left rail. Choose which AI model refines your prompts. Claude Sonnet 4.6 is the default.' },
      { type: 'list', items: [
        { label: 'Claude Opus 4.7', text: 'Most capable. Best for complex prompts and the most careful scoring.' },
        { label: 'Claude Sonnet 4.6', text: 'Default. Balanced workhorse.' },
        { label: 'Claude Opus 4.6', text: 'The previous flagship.' },
        { label: 'Claude Haiku 4.5', text: 'Fastest and cheapest. Scores tend to be less nuanced.' },
      ]},
    ],
  },
  {
    id: 'shortcuts',
    title: 'Keyboard shortcuts',
    body: [
      { type: 'list', items: [
        { label: 'Cmd+Enter (in composer)', text: 'Submit a new refinement.' },
        { label: 'Cmd+Enter (in follow-up)', text: 'Apply your feedback.' },
        { label: 'Enter (in rename)', text: 'Save a new name for a saved prompt.' },
        { label: 'Escape (in rename)', text: 'Cancel renaming.' },
      ]},
    ],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    body: [
      { type: 'list', items: [
        { label: '"Something went wrong"', text: 'Backend server isn\'t running, or API key is invalid.' },
        { label: 'Missing scores panel', text: 'Occasionally the AI emits an unparseable JSON block. The refined prompt and changes still work.' },
        { label: 'Scores feel inconsistent', text: 'Score values can shift between runs of the same prompt — the model is making subjective judgments. Treat them as directional.' },
        { label: 'Slow first chunk', text: 'The AI takes a moment to start. Streaming should be smooth after the first words.' },
        { label: 'History/Saved disappeared', text: 'Most likely your browser cleared its local data.' },
      ]},
    ],
  },
];
