import { useState, useEffect, useMemo } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { CloseIcon, CheckIcon, ExternalLinkIcon, DownloadIcon } from './icons.jsx';
import { SCORE_DIMENSIONS } from './constants.js';
import {
  defaultPDFFilename, sanitizeFilename,
  modelShortName, computeCost, formatCost, formatLatency, averageScore,
} from './utils.js';

const PDF_SECTIONS = [
  { id: 'rough',      label: 'Rough prompt'      },
  { id: 'refined',    label: 'Refined prompt'    },
  { id: 'changes',    label: 'What changed'      },
  { id: 'scores',     label: 'Quality scores'    },
  { id: 'abtest',     label: 'A/B test results'  },
  { id: 'comparison', label: 'Model comparison'  },
];

export function PDFPreviewModal({
  roughPrompt, category, refinedPrompt, changes, scores,
  primaryModel, primaryUsage, primaryLatencyMs,
  abTest, testModel, comparison, scoresChartRef, onClose,
}) {
  const [filename, setFilename] = useState(defaultPDFFilename());
  const [pdfBlob, setPdfBlob] = useState(null);
  const [pdfUrl, setPdfUrl] = useState(null);
  const [status, setStatus] = useState('generating');
  const [errorMsg, setErrorMsg] = useState('');

  const abTestPresent    = Boolean(abTest && (abTest.refined?.complete || abTest.rough?.complete));
  const comparisonPresent = Boolean(comparison?.columns?.length);

  const [sections, setSections] = useState(() => ({
    rough:      Boolean(roughPrompt),
    refined:    Boolean(refinedPrompt),
    changes:    Boolean(changes?.length),
    scores:     Boolean(scores?.refined),
    abtest:     abTestPresent,
    comparison: comparisonPresent,
  }));

  function toggleSection(id) {
    setSections((prev) => ({ ...prev, [id]: !prev[id] }));
  }

  const availableSections = useMemo(() => {
    const out = [];
    if (roughPrompt)      out.push('rough');
    if (refinedPrompt)    out.push('refined');
    if (changes?.length)  out.push('changes');
    if (scores?.refined)  out.push('scores');
    if (abTestPresent)    out.push('abtest');
    if (comparisonPresent) out.push('comparison');
    return out;
  }, [roughPrompt, refinedPrompt, changes, scores, abTestPresent, comparisonPresent]);

  useEffect(() => {
    let cancelled = false;
    const timer = setTimeout(() => {
      if (cancelled) return;
      generatePDF();
    }, 250);
    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sections]);

  useEffect(() => {
    return () => {
      if (pdfUrl) URL.revokeObjectURL(pdfUrl);
    };
  }, [pdfUrl]);

  async function generatePDF() {
    try {
      setStatus('generating');

      if (pdfUrl) {
        URL.revokeObjectURL(pdfUrl);
        setPdfUrl(null);
      }

      await new Promise((resolve) => requestAnimationFrame(resolve));

      let chartImageData = null;
      if (sections.scores && scoresChartRef?.current) {
        try {
          const canvas = await html2canvas(scoresChartRef.current, {
            backgroundColor: '#ffffff',
            scale: 2,
            logging: false,
            useCORS: true,
          });
          chartImageData = canvas.toDataURL('image/png');
        } catch (err) {
          console.warn('Chart rasterization failed, continuing without chart image:', err);
        }
      }

      const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'letter' });
      const pageWidth  = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin       = 54;
      const contentWidth = pageWidth - margin * 2;
      let y = margin;

      function ensureSpace(needed) {
        if (y + needed > pageHeight - margin - 20) {
          addFooter();
          doc.addPage();
          y = margin;
        }
      }

      function addFooter() {
        const currentPage = doc.internal.getCurrentPageInfo().pageNumber;
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.setFont('helvetica', 'normal');
        doc.text('Generated by Prompt Refina', margin, pageHeight - margin / 2);
        doc.text(`Page ${currentPage}`, pageWidth - margin, pageHeight - margin / 2, { align: 'right' });
      }

      function drawSectionHeader(label) {
        ensureSpace(40);
        doc.setFontSize(10);
        doc.setTextColor(120);
        doc.setFont('helvetica', 'bold');
        doc.text(label, margin, y);
        y += 14;
      }

      function drawParagraphChunked(text, fontSize, color, italic = false) {
        doc.setFontSize(fontSize);
        doc.setTextColor(color);
        doc.setFont('helvetica', italic ? 'italic' : 'normal');
        const lines = doc.splitTextToSize(text || '(empty)', contentWidth);
        const lineHeight = fontSize + 3;
        let i = 0;
        while (i < lines.length) {
          const remaining = pageHeight - margin - 20 - y;
          const linesFit = Math.max(1, Math.floor(remaining / lineHeight));
          const chunk = lines.slice(i, i + linesFit);
          doc.text(chunk, margin, y);
          y += chunk.length * lineHeight;
          i += chunk.length;
          if (i < lines.length) {
            addFooter();
            doc.addPage();
            y = margin;
          }
        }
      }

      // Document header
      doc.setFontSize(9);
      doc.setTextColor(120);
      doc.setFont('helvetica', 'normal');
      doc.text('PROMPT REFINERY', margin, y);
      const dateStr = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
      doc.text(dateStr, pageWidth - margin, y, { align: 'right' });
      y += 8;

      doc.setDrawColor(220);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 24;

      doc.setFontSize(20);
      doc.setTextColor(40);
      doc.setFont('helvetica', 'bold');
      doc.text('Refined Prompt', margin, y);
      y += 22;

      doc.setFontSize(9);
      doc.setTextColor(120);
      doc.setFont('helvetica', 'normal');
      doc.text([`Model: ${modelShortName(primaryModel)}`, `Category: ${category}`].join('   •   '), margin, y);
      y += 24;

      if (sections.rough && roughPrompt) {
        drawSectionHeader('ROUGH PROMPT');
        drawParagraphChunked(roughPrompt, 10, 90, true);
        y += 14;
      }

      if (sections.refined && refinedPrompt) {
        drawSectionHeader('REFINED PROMPT');
        drawParagraphChunked(refinedPrompt, 11, 40, false);
        y += 14;
      }

      if (sections.changes && changes?.length > 0) {
        drawSectionHeader('WHAT CHANGED');
        changes.forEach((change, idx) => {
          const numStr = `${idx + 1}.`;
          const titleLines = doc.splitTextToSize(change.title || '', contentWidth - 22);
          const explLines  = doc.splitTextToSize(change.explanation || '', contentWidth - 22);
          ensureSpace(titleLines.length * 13 + explLines.length * 12 + 14);

          doc.setFontSize(10); doc.setTextColor(180, 100, 70); doc.setFont('helvetica', 'bold');
          doc.text(numStr, margin, y);
          doc.setTextColor(40); doc.setFont('helvetica', 'bold');
          doc.text(titleLines, margin + 18, y);
          y += titleLines.length * 13;

          doc.setFontSize(9.5); doc.setTextColor(90); doc.setFont('helvetica', 'normal');
          doc.text(explLines, margin + 18, y);
          y += explLines.length * 12 + 10;
        });
        y += 8;
      }

      if (sections.scores && scores?.refined) {
        drawSectionHeader('QUALITY SCORE');

        const roughAvg   = averageScore(scores.rough);
        const refinedAvg = averageScore(scores.refined);
        const lift = (roughAvg !== null && refinedAvg !== null) ? refinedAvg - roughAvg : null;

        doc.setFontSize(11); doc.setTextColor(40); doc.setFont('helvetica', 'normal');
        let summary = roughAvg !== null ? `Rough: ${roughAvg.toFixed(1)}/5   →   ` : '';
        summary += `Refined: ${refinedAvg.toFixed(1)}/5`;
        if (lift !== null && lift > 0) summary += `   (+${lift.toFixed(1)} lift)`;
        doc.text(summary, margin, y);
        y += 18;

        if (chartImageData) {
          const chartMaxHeight = 200;
          ensureSpace(chartMaxHeight + 10);
          try {
            doc.addImage(chartImageData, 'PNG', margin, y, contentWidth, chartMaxHeight, undefined, 'FAST');
            y += chartMaxHeight + 14;
          } catch (err) {
            console.warn('Chart embed failed:', err);
          }
        }

        SCORE_DIMENSIONS.forEach((d) => {
          const refined = scores.refined?.[d.id];
          const rough   = scores.rough?.[d.id];
          if (!refined) return;
          const refScoreStr   = `${refined.score}/5`;
          const roughScoreStr = rough?.score !== undefined ? `${rough.score} → ` : '';
          ensureSpace(34);
          doc.setFontSize(10); doc.setTextColor(40); doc.setFont('helvetica', 'bold');
          doc.text(d.label, margin, y);
          doc.setFont('helvetica', 'normal'); doc.setTextColor(120);
          doc.text(`${roughScoreStr}${refScoreStr}`, pageWidth - margin, y, { align: 'right' });
          y += 12;
          if (refined.rationale) {
            doc.setFontSize(9); doc.setTextColor(110); doc.setFont('helvetica', 'normal');
            const ratLines = doc.splitTextToSize(refined.rationale, contentWidth);
            ensureSpace(ratLines.length * 11 + 4);
            doc.text(ratLines, margin, y);
            y += ratLines.length * 11 + 6;
          }
        });
        y += 8;
      }

      if (sections.abtest && abTestPresent) {
        drawSectionHeader('A/B TEST RESULTS');
        doc.setFontSize(9.5); doc.setTextColor(110); doc.setFont('helvetica', 'italic');
        const testHeader = `Outputs from ${modelShortName(testModel)}. Comparing what the rough vs refined prompt actually produces.`;
        const testHeaderLines = doc.splitTextToSize(testHeader, contentWidth);
        doc.text(testHeaderLines, margin, y);
        y += testHeaderLines.length * 11 + 10;

        if (abTest.rough?.text) {
          ensureSpace(40);
          doc.setFontSize(10); doc.setTextColor(150); doc.setFont('helvetica', 'bold');
          doc.text('From rough prompt', margin, y);
          doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(140);
          const roughCost = abTest.rough?.usage ? computeCost(testModel, abTest.rough.usage) : null;
          const roughMeta = [
            roughCost !== null ? formatCost(roughCost) : null,
            abTest.rough?.latencyMs ? formatLatency(abTest.rough.latencyMs) : null,
          ].filter(Boolean).join('   •   ');
          if (roughMeta) doc.text(roughMeta, pageWidth - margin, y, { align: 'right' });
          y += 14;
          drawParagraphChunked(abTest.rough.text, 10, 60, false);
          y += 16;
        }

        if (abTest.refined?.text) {
          ensureSpace(40);
          doc.setFontSize(10); doc.setTextColor(180, 100, 70); doc.setFont('helvetica', 'bold');
          doc.text('From refined prompt', margin, y);
          doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(140);
          const refinedCost = abTest.refined?.usage ? computeCost(testModel, abTest.refined.usage) : null;
          const refinedMeta = [
            refinedCost !== null ? formatCost(refinedCost) : null,
            abTest.refined?.latencyMs ? formatLatency(abTest.refined.latencyMs) : null,
          ].filter(Boolean).join('   •   ');
          if (refinedMeta) doc.text(refinedMeta, pageWidth - margin, y, { align: 'right' });
          y += 14;
          drawParagraphChunked(abTest.refined.text, 10, 40, false);
          y += 16;
        }
      }

      if (sections.comparison && comparisonPresent) {
        drawSectionHeader('MODEL COMPARISON');
        doc.setFontSize(9.5); doc.setTextColor(110); doc.setFont('helvetica', 'italic');
        const compHeader = `Same rough prompt refined by ${comparison.columns.length + 1} models. Primary refinement shown first, then alternates.`;
        const compHeaderLines = doc.splitTextToSize(compHeader, contentWidth);
        doc.text(compHeaderLines, margin, y);
        y += compHeaderLines.length * 11 + 12;

        comparison.columns.forEach((col) => {
          if (col.error) {
            ensureSpace(36);
            doc.setFontSize(10); doc.setTextColor(180, 80, 80); doc.setFont('helvetica', 'bold');
            doc.text(`${modelShortName(col.modelId)} (failed)`, margin, y);
            y += 12;
            doc.setFontSize(9); doc.setTextColor(140); doc.setFont('helvetica', 'normal');
            const errLines = doc.splitTextToSize(col.error, contentWidth);
            doc.text(errLines, margin, y);
            y += errLines.length * 11 + 14;
            return;
          }
          ensureSpace(40);
          doc.setFontSize(11); doc.setTextColor(180, 100, 70); doc.setFont('helvetica', 'bold');
          doc.text(modelShortName(col.modelId), margin, y);
          const colCost  = col.usage ? computeCost(col.modelId, col.usage) : null;
          const colScore = averageScore(col.scores?.refined);
          const colMeta  = [
            colScore !== null ? `${colScore.toFixed(1)}/5` : null,
            colCost  !== null ? formatCost(colCost) : null,
            col.latencyMs ? formatLatency(col.latencyMs) : null,
          ].filter(Boolean).join('   •   ');
          if (colMeta) {
            doc.setFontSize(9); doc.setTextColor(140); doc.setFont('helvetica', 'normal');
            doc.text(colMeta, pageWidth - margin, y, { align: 'right' });
          }
          y += 16;
          if (col.refined) { drawParagraphChunked(col.refined, 10, 40, false); y += 8; }
          if (col.changes?.length > 0) {
            ensureSpace(30);
            doc.setFontSize(9); doc.setTextColor(120); doc.setFont('helvetica', 'bold');
            doc.text('Changes:', margin, y);
            y += 12;
            col.changes.forEach((c, i) => {
              const cTitleLines = doc.splitTextToSize(`${i + 1}. ${c.title || ''}`, contentWidth - 8);
              const cExplLines  = doc.splitTextToSize(c.explanation || '', contentWidth - 16);
              ensureSpace(cTitleLines.length * 11 + cExplLines.length * 10 + 10);
              doc.setFontSize(9.5); doc.setTextColor(60); doc.setFont('helvetica', 'bold');
              doc.text(cTitleLines, margin, y);
              y += cTitleLines.length * 11;
              doc.setFontSize(9); doc.setTextColor(110); doc.setFont('helvetica', 'normal');
              doc.text(cExplLines, margin + 8, y);
              y += cExplLines.length * 10 + 6;
            });
          }
          y += 12;
        });
      }

      addFooter();
      const blob = doc.output('blob');
      const url  = URL.createObjectURL(blob);
      setPdfBlob(blob);
      setPdfUrl(url);
      setStatus('ready');
    } catch (err) {
      console.error('PDF generation failed:', err);
      setErrorMsg(err.message || 'PDF generation failed.');
      setStatus('error');
    }
  }

  function handleDownload() {
    if (!pdfBlob) return;
    const safe      = sanitizeFilename(filename);
    const finalName = safe.endsWith('.pdf') ? safe : `${safe}.pdf`;
    const link = document.createElement('a');
    link.href = URL.createObjectURL(pdfBlob);
    link.download = finalName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setTimeout(() => URL.revokeObjectURL(link.href), 1000);
    setTimeout(() => onClose(), 250);
  }

  function handleOpenInNewTab() {
    if (!pdfUrl) return;
    window.open(pdfUrl, '_blank', 'noopener,noreferrer');
  }

  function handleBackdropClick(e) {
    if (e.target === e.currentTarget) onClose();
  }

  const sectionCount    = availableSections.filter((id) => sections[id]).length;
  const allSectionsCount = availableSections.length;

  return (
    <div className="modal-backdrop" onClick={handleBackdropClick}>
      <div className="modal pdf-modal" role="dialog" aria-modal="true" aria-labelledby="pdf-title">
        <div className="modal-head">
          <h2 id="pdf-title">Preview & download PDF</h2>
          <button className="modal-close" onClick={onClose} aria-label="Close" title="Close">
            <CloseIcon />
          </button>
        </div>

        <div className="pdf-sections-panel">
          <div className="pdf-sections-label">
            Sections to include ({sectionCount} of {allSectionsCount})
          </div>
          <div className="pdf-sections-list">
            {PDF_SECTIONS.map((s) => {
              const available = availableSections.includes(s.id);
              if (!available) return null;
              const checked = sections[s.id];
              return (
                <button
                  type="button"
                  key={s.id}
                  className={`pdf-section-chip ${checked ? 'on' : ''}`}
                  onClick={() => toggleSection(s.id)}
                  disabled={status === 'generating'}
                >
                  <span className="pdf-section-chip-check">
                    {checked && <CheckIcon />}
                  </span>
                  <span>{s.label}</span>
                </button>
              );
            })}
          </div>
        </div>

        <div className="pdf-modal-body">
          {status === 'generating' && (
            <div className="pdf-loading">
              <span className="thinking-dots">
                <span className="thinking-dot"></span>
                <span className="thinking-dot"></span>
                <span className="thinking-dot"></span>
              </span>
              <span>Generating PDF preview…</span>
            </div>
          )}

          {status === 'error' && (
            <div className="pdf-error">
              <strong>PDF generation failed.</strong>
              <div>{errorMsg}</div>
              <div className="pdf-error-hint">
                Check the browser console for details. You can close this dialog and try again.
              </div>
            </div>
          )}

          {status === 'ready' && pdfUrl && (
            <iframe src={pdfUrl} className="pdf-preview-frame" title="PDF preview" />
          )}
        </div>

        <div className="modal-foot pdf-modal-foot">
          <div className="pdf-filename-row">
            <label htmlFor="pdf-filename" className="pdf-filename-label">Filename</label>
            <input
              id="pdf-filename"
              type="text"
              className="pdf-filename-input"
              value={filename}
              onChange={(e) => setFilename(e.target.value)}
              placeholder={defaultPDFFilename()}
              disabled={status !== 'ready'}
            />
            <span className="pdf-filename-ext">.pdf</span>
          </div>
          <div className="pdf-modal-actions">
            <button className="pii-modal-btn pii-modal-btn-secondary" onClick={onClose}>
              Cancel
            </button>
            <button
              className="pii-modal-btn pii-modal-btn-secondary"
              onClick={handleOpenInNewTab}
              disabled={status !== 'ready'}
              title="Open in a new tab where text selection works"
            >
              <ExternalLinkIcon />
              <span>Open in new tab</span>
            </button>
            <button
              className="pii-modal-btn pii-modal-btn-primary"
              onClick={handleDownload}
              disabled={status !== 'ready'}
            >
              <DownloadIcon />
              <span>Download PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
